### ISSUE TITLE
openEditor doesn't trigger the success callback

### ISSUE THREAD

**Issue by llittlefoxx** [imgly/pesdk-cordova#1]
It would be great if you could add the success callback call to the present function.
The successful call of the plugin doesn't trigger the success callback. I checked the native code and the a cordova success result is not triggered in the present function.

**Comment by svendvd** [comment]
We don't answer any problems in Github. I would ask you to use the ticket system instead: https://imglysdk.atlassian.net/servicedesk/customer/portal/1
